targets:
    linux: []
    macos:
        - name: macos-x86_64
          platform: macos
          platform_version: x86_64
          family: generic
          arch: x86_64
          runs_on: [macos-14]
        - name: macos-aarch64
          platform: macos
          platform_version: aarch64
          family: generic
          arch: aarch64
          runs_on: [macos-14]

    win: []
