targets:
    linux:
        - name: debian-stretch
          platform: debian
          platform_version: stretch
          family: debian
        - name: debian-buster
          platform: debian
          platform_version: buster
          family: debian
        - name: debian-bullseye
          platform: debian
          platform_version: bullseye
          family: debian
        - name: ubuntu-xenial
          platform: ubuntu
          platform_version: xenial
          family: debian
        - name: ubuntu-bionic
          platform: ubuntu
          platform_version: bionic
          family: debian
        - name: ubuntu-focal
          platform: ubuntu
          platform_version: focal
          family: debian
        - name: ubuntu-jammy
          platform: ubuntu
          platform_version: jammy
          family: debian
        - name: centos-7
          platform: centos
          platform_version: 7
          family: redhat
        - name: centos-8
          platform: centos
          platform_version: 8
          family: redhat
        - name: linux-x86_64
          platform: linux
          platform_version: x86_64
          platform_libc: musl
          family: generic

    macos:
        - name: macos-x86_64
          platform: macos
          platform_version: x86_64
          family: generic

        - name: macos-aarch64
          platform: macos
          platform_version: aarch64
          family: generic
          runs_on: [self-hosted, macOS, ARM64]

    win:
       - name: win-x86_64
         platform: win
         platform_version: x86_64
