<% from "build.inc.yml" import workflow -%>
name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:
  <<- workflow(targets, subdist="nightly") ->>
